services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: railsapi_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/railsapi_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
