---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/todos":
    get:
      summary: List all todos
      tags:
      - Todos
      responses:
        '200':
          description: todos found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    completed:
                      type: boolean
                    created_at:
                      type: string
                      format: datetime
                    updated_at:
                      type: string
                      format: datetime
                  required:
                  - id
                  - title
                  - completed
                  - created_at
                  - updated_at
    post:
      summary: Create a todo
      tags:
      - Todos
      parameters: []
      responses:
        '201':
          description: todo created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                required:
                - id
                - title
                - completed
                - created_at
                - updated_at
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
              required:
              - title
  "/api/v1/todos/{id}":
    parameters:
    - name: id
      in: path
      description: Todo ID
      required: true
      schema:
        type: integer
    get:
      summary: Show a todo
      tags:
      - Todos
      responses:
        '200':
          description: todo found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                required:
                - id
                - title
                - completed
                - created_at
                - updated_at
        '404':
          description: todo not found
    put:
      summary: Update a todo
      tags:
      - Todos
      parameters: []
      responses:
        '200':
          description: todo updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                required:
                - id
                - title
                - completed
                - created_at
                - updated_at
        '422':
          description: invalid request
        '404':
          description: todo not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
    delete:
      summary: Delete a todo
      tags:
      - Todos
      responses:
        '204':
          description: todo deleted
        '404':
          description: todo not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
